import '../domain/operation_type.dart';
import 'challenge.dart';

/// In-memory challenge set.
///
/// Count and Shift are the hybrid prototype: the target is a number.
/// Count teaches what each cell is worth by toggling cells; Shift reaches
/// the number with doubling (Shift Left) and halving (Shift Right), where
/// bits pushed off either end are lost — so the shortest route is often
/// not the obvious one. Preserve and Transform keep the original
/// bit-pattern targets.
///
/// This is still a prototype set, not SRA-BR-005's 40 challenges; every
/// entry is machine-checked as solvable within its budget
/// (test/content/challenge_solvability_test.dart, SRA-TR-004).
class ChallengeRepository {
  const ChallengeRepository._();

  /// Extra moves the Shift chapter's budget gives beyond each puzzle's par
  /// (its shortest solution) — room to recover from a wrong shift without
  /// failing the round. [PracticeScoring] scores how much of it gets used.
  static const shiftSlack = 2;

  static const List<Challenge> all = [
    Challenge(
      id: 'count-01',
      chapter: 'Count',
      title: 'Make 2',
      initialBits: 0,
      targetBits: 2,
      allowedOperations: [],
      moveBudget: 3,
      targetStyle: TargetStyle.number,
      toggleable: true,
      clocked: false,
    ),
    Challenge(
      id: 'count-02',
      chapter: 'Count',
      title: 'Make 1',
      initialBits: 0,
      targetBits: 1,
      allowedOperations: [],
      moveBudget: 3,
      targetStyle: TargetStyle.number,
      toggleable: true,
      clocked: false,
    ),
    Challenge(
      id: 'count-03',
      chapter: 'Count',
      title: 'Make 4',
      initialBits: 0,
      targetBits: 4,
      allowedOperations: [],
      moveBudget: 3,
      targetStyle: TargetStyle.number,
      toggleable: true,
      clocked: false,
    ),
    Challenge(
      id: 'count-04',
      chapter: 'Count',
      title: 'Make 3',
      initialBits: 0,
      targetBits: 3,
      allowedOperations: [],
      moveBudget: 4,
      targetStyle: TargetStyle.number,
      toggleable: true,
    ),
    Challenge(
      id: 'count-05',
      chapter: 'Count',
      title: 'Make 5',
      initialBits: 0,
      targetBits: 5,
      allowedOperations: [],
      moveBudget: 4,
      targetStyle: TargetStyle.number,
      toggleable: true,
    ),
    Challenge(
      id: 'count-06',
      chapter: 'Count',
      title: 'Make 8',
      initialBits: 0,
      targetBits: 8,
      allowedOperations: [],
      moveBudget: 3,
      targetStyle: TargetStyle.number,
      toggleable: true,
    ),
    Challenge(
      id: 'count-07',
      chapter: 'Count',
      title: 'Make 6',
      initialBits: 5,
      targetBits: 6,
      allowedOperations: [],
      moveBudget: 4,
      targetStyle: TargetStyle.number,
      toggleable: true,
    ),
    Challenge(
      id: 'count-08',
      chapter: 'Count',
      title: 'Make 12',
      initialBits: 0,
      targetBits: 12,
      allowedOperations: [],
      moveBudget: 4,
      targetStyle: TargetStyle.number,
      toggleable: true,
    ),
    Challenge(
      id: 'count-09',
      chapter: 'Count',
      title: 'Make 10',
      initialBits: 7,
      targetBits: 10,
      allowedOperations: [],
      moveBudget: 5,
      targetStyle: TargetStyle.number,
      toggleable: true,
    ),
    Challenge(
      id: 'count-10',
      chapter: 'Count',
      title: 'Make 25',
      initialBits: 0,
      targetBits: 25,
      allowedOperations: [],
      moveBudget: 5,
      targetStyle: TargetStyle.number,
      toggleable: true,
    ),
    Challenge(
      id: 'shift-01',
      chapter: 'Shift',
      title: 'Double',
      initialBits: 3,
      targetBits: 6,
      allowedOperations: [OperationType.shiftLeft, OperationType.shiftRight],
      moveBudget: 1 + shiftSlack,
      parMoves: 1,
      targetStyle: TargetStyle.number,
      clocked: false,
    ),
    Challenge(
      id: 'shift-02',
      chapter: 'Shift',
      title: 'Double Again',
      initialBits: 3,
      targetBits: 12,
      allowedOperations: [OperationType.shiftLeft, OperationType.shiftRight],
      moveBudget: 2 + shiftSlack,
      parMoves: 2,
      targetStyle: TargetStyle.number,
    ),
    Challenge(
      id: 'shift-03',
      chapter: 'Shift',
      title: 'Halve',
      initialBits: 12,
      targetBits: 6,
      allowedOperations: [OperationType.shiftLeft, OperationType.shiftRight],
      moveBudget: 1 + shiftSlack,
      parMoves: 1,
      targetStyle: TargetStyle.number,
    ),
    Challenge(
      id: 'shift-04',
      chapter: 'Shift',
      title: 'Halve Twice',
      initialBits: 80,
      targetBits: 20,
      allowedOperations: [OperationType.shiftLeft, OperationType.shiftRight],
      moveBudget: 2 + shiftSlack,
      parMoves: 2,
      targetStyle: TargetStyle.number,
    ),
    Challenge(
      id: 'shift-05',
      chapter: 'Shift',
      title: 'Odd One Out',
      initialBits: 13,
      targetBits: 6,
      allowedOperations: [OperationType.shiftLeft, OperationType.shiftRight],
      moveBudget: 1 + shiftSlack,
      parMoves: 1,
      targetStyle: TargetStyle.number,
    ),
    Challenge(
      id: 'shift-06',
      chapter: 'Shift',
      title: 'Lose the Low Bit',
      initialBits: 11,
      targetBits: 10,
      allowedOperations: [OperationType.shiftLeft, OperationType.shiftRight],
      moveBudget: 2 + shiftSlack,
      parMoves: 2,
      targetStyle: TargetStyle.number,
    ),
    Challenge(
      id: 'shift-07',
      chapter: 'Shift',
      title: 'Top Falls Off',
      initialBits: 130,
      targetBits: 4,
      allowedOperations: [OperationType.shiftLeft, OperationType.shiftRight],
      moveBudget: 1 + shiftSlack,
      parMoves: 1,
      targetStyle: TargetStyle.number,
    ),
    Challenge(
      id: 'shift-08',
      chapter: 'Shift',
      title: 'Clear the Top',
      initialBits: 200,
      targetBits: 72,
      allowedOperations: [OperationType.shiftLeft, OperationType.shiftRight],
      moveBudget: 2 + shiftSlack,
      parMoves: 2,
      targetStyle: TargetStyle.number,
    ),
    Challenge(
      id: 'shift-09',
      chapter: 'Shift',
      title: 'Trim Both Ends',
      initialBits: 27,
      targetBits: 12,
      allowedOperations: [OperationType.shiftLeft, OperationType.shiftRight],
      moveBudget: 3 + shiftSlack,
      parMoves: 3,
      targetStyle: TargetStyle.number,
    ),
    Challenge(
      id: 'shift-10',
      chapter: 'Shift',
      title: 'Squeeze',
      initialBits: 255,
      targetBits: 120,
      allowedOperations: [OperationType.shiftLeft, OperationType.shiftRight],
      moveBudget: 5 + shiftSlack,
      parMoves: 5,
      targetStyle: TargetStyle.number,
    ),
    Challenge(
      id: 'preserve-01',
      chapter: 'Preserve',
      title: 'Full Circle',
      initialBits: 0x03,
      targetBits: 0x81,
      allowedOperations: [OperationType.rotateLeft, OperationType.rotateRight],
      moveBudget: 1,
    ),
    Challenge(
      id: 'preserve-02',
      chapter: 'Preserve',
      title: 'Rotate Into Place',
      initialBits: 0x01,
      targetBits: 0x10,
      allowedOperations: [OperationType.rotateLeft],
      moveBudget: 4,
    ),
    Challenge(
      id: 'transform-01',
      chapter: 'Transform',
      title: 'Keep the High Nibble',
      initialBits: 0xF7,
      targetBits: 0xF0,
      allowedOperations: [OperationType.maskAnd],
      moveBudget: 1,
      maskOperand: 0xF0,
    ),
  ];

  static Challenge byId(String id) => all.firstWhere((c) => c.id == id);
}
